---
title: "DEA"
output:
  html_document:
    df_print: paged
  html_notebook:
    highlight: textmate
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(Benchmarking)
```

```{r}
x <- matrix(c(150, 400, 320, 520, 350, 320, .2, .7, 1.2, 2.0, 1.2, .7), ncol = 2)
y <- matrix(c(14000, 14000, 42000, 28000, 19000, 14000, 3500, 21000, 10500, 42000, 25000, 15000),ncol = 2)
colnames(y) <- c("Reimbursed Patient-Days","Privately Paid Patient-Days")
colnames(x) <- c("Staff Hours Per day", "Supplies Per Day")
x
y
```

```{r}
e_crs <- dea(x, y, RTS = "crs", ORIENTATION = "in")
eff(e_crs)
peers(e_crs)
peers(e_crs, NAMES = TRUE)
print(peers(e_crs, NAMES = TRUE), quote = FALSE)
lambda(e_crs)
summary(e_crs)
dea.plot.isoquant(x,y,RTS="crs")
```

```{r}
e_vrs <- dea(x, y, RTS = "vrs", ORIENTATION = "in")
eff(e_vrs)
peers(e_vrs)
peers(e_vrs, NAMES = TRUE)
print(peers(e_vrs, NAMES = TRUE), quote = FALSE)
lambda(e_vrs)
summary(e_vrs)
dea.plot.isoquant(x,y,RTS="vrs")
```

```{r}
e_fdh <- dea(x, y, RTS = "fdh", ORIENTATION = "in")
eff(e_fdh)
peers(e_fdh)
peers(e_fdh, NAMES = TRUE)
print(peers(e_fdh, NAMES = TRUE), quote = FALSE)
lambda(e_fdh)
summary(e_fdh)
dea.plot.isoquant(x,y,RTS="fdh")
```

```{r}
e_irs <- dea(x, y, RTS = "irs", ORIENTATION = "in")
eff(e_irs)
peers(e_irs)
peers(e_irs, NAMES = TRUE)
print(peers(e_irs, NAMES = TRUE), quote = FALSE)
lambda(e_irs)
summary(e_irs)
dea.plot.isoquant(x,y,RTS="irs")
```

```{r}
e_irs2 <- dea(x, y, RTS = "irs2", ORIENTATION = "in")
eff(e_irs2)
peers(e_irs2)
peers(e_irs2, NAMES = TRUE)
print(peers(e_irs2, NAMES = TRUE), quote = FALSE)
lambda(e_irs2)
summary(e_irs2)
dea.plot.isoquant(x,y,RTS="irs2")
```

```{r}
e_drs <- dea(x, y, RTS = "drs", ORIENTATION = "in")
eff(e_drs)
peers(e_drs)
peers(e_drs, NAMES = TRUE)
print(peers(e_drs, NAMES = TRUE), quote = FALSE)
lambda(e_drs)
summary(e_drs)
dea.plot.isoquant(x,y,RTS="drs")
```

```{r}
e_frh <- dea(x, y, RTS = "add", ORIENTATION = "in")
eff(e_frh)
peers(e_frh)
peers(e_frh, NAMES = TRUE)
print(peers(e_frh, NAMES = TRUE), quote = FALSE)
lambda(e_frh)
summary(e_frh)
```

```{r}
e_fdh2 <- dea(x, y, RTS = "fdh+", ORIENTATION = "in")
eff(e_fdh2)
peers(e_fdh2)
peers(e_fdh2, NAMES = TRUE)
print(peers(e_fdh2, NAMES = TRUE), quote = FALSE)
lambda(e_fdh2)
summary(e_fdh2)
```

Results have been summarized by using summary function.
</br>
</br>
The results indicate that e_fdh, e_irs2, e_frh & e_fdh2 are the most efficient. </br>
e_drs & e_crs have a mean efficiency of .974</br>
e_irs and e_vrs have a mean efficienct of .983</br>